### ISSUE TITLE
리뷰어 자동설정

### ISSUE THREAD

**Issue by Cha-Ji** [GDSC-PKNU-21-22/gdsc_pknu_front#12]
## To Do
- gdsc에 프론트팀을 생성한다.
- root directory에 CODEOWNER 파일을 만들어 프론트팀을 태그한다.
  - 여기서, 유저 id를 각각 태그해도 좋다.

**Comment by turtle601** [comment]
이게 뭐죵?? 어떤 기능인가요

**Comment by Cha-Ji** [comment]
> 이게 뭐죵?? 어떤 기능인가요

PR을 올릴 때 리뷰어를 자동으로 태그해주는 기능입니다.
